version: '3.7'
services:
  ###############################################
  ########## external container #################
  ###############################################
    mongodb:
      image: ${LIA_dockerimage}
      container_name: ${LIA_MONGO_CONTAINER}
      ports:
        -  ${LIA_MONGO_PORT}:${LIA_MONGO_PORT}
      env_file:
        - .env

    mosquitto:
      image: eclipse-mosquitto
      container_name: mosquitto
      ports:
        -  "1884:1884"

  ########## LIA OVGU CONTAINERS #################
    vws_aas_registry:
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        -  ${LIA_AAS_RESTAPI_PORT_EXTERN}:${LIA_AAS_RESTAPI_PORT_INTERN}
      environment:
        -  REGISTRY_DATABASE_HOST=${LIA_MONGO_CONTAINER}
      volumes:
        - ./logs:/vws_aas_registry/src/main/logs
